name: python package CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.versions.os }}
    strategy:
      matrix:
        versions:
          - { python-version: '3.12', os: ubuntu-20.04 }

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==1.7.0

      - name: Set up Python ${{ matrix.versions.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.versions.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install -E toml -E yaml

      - name: Run tests
        run: |
          poetry run pytest -cov=config_file/ --cov-report=term-missing
          poetry run coverage xml -o coverage.xml
          ls

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Build Package
        run: poetry build
